version: "3"
services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=root
 docker-sql:
   build: .
  ports:
    - "8080:8080"
  depends_on:
    - docker-mysql

